enabled: true
top_level_version: false
show_all_pages: false
home_url: 'http://phpvms.net'
github:
  position: top
  tree: 'https://github.com/phpvms/docs/tree/master'
  commits: 'https://github.com/phpvms/docs/commits/master'
