title: 'phpVMS Documentation'
default_lang: en
taxonomies:
  - category
  - tag
metadata:
  description: 'phpvms docs'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
